### ISSUE TITLE
Finish Switchboard version 2

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/switchboard#310]

**Comment by froid1911** [comment]
DoD:
- [ x ] uses the reactor api 
- [ ]  provides example read model for searching documents


Replace Current switchboard with the evolving MVP. See the following Issues for completion 

- [x] powerhouse-inc/switchboard#311
- [ ] #304 
- [ ] #305
- [x] #306
- [x] #307  
- [x] #308  
- [ ] #309 

- Drizzle storage adapter
- Copy & improve prisma database (Test needed before migration) 
- Ongoing discussions on the indexing mechanism
- Subgraph work & configuration 


@CallmeT-ty to check demo priorities impact on Switchboard workload. (search bar functionality)
